### ISSUE TITLE
Purge offensive language from Metal3-io repositories

### ISSUE THREAD

**Issue by maelk** [metal3-io/metal3-docs#117]
Following a K8s-wide effort to remove terms such as "master", "slave", "whitelist" and "blacklist", we should take steps to remove this type of words from our repos. In K8S repos, the Github "master" branches will be renamed to "main". 

We should follow the movement and remove at least those four words with the following proposed replacements:

- master -> controlplane
- slave -> worker
- whitelist -> allowlist
- blacklist -> denylist

we should also rename all our master branches to main.

**Comment by dhellmann** [comment]
It would be good to handle the branch renaming in all of our repos quickly to minimize disruption. I imagine a couple of us with admin privileges could go through and do that. Does the k8s community have a set of instructions worked out?

What other changes would we need to make? Does CI need to be reconfigured at the same time?

**Comment by demonCoder95** [comment]
It's a questionable move by Github and others in my opinion, changing terminology will not have the desired affect, at all. These are problems of perception and human behaviors, not words. It will only cause software breakage all over the place, adding to the already humongous mess of terminology that has already been in place since forever.

However, the proposed changes look reasonable. So, LGTM. +1

**Comment by maelk** [comment]
This is also a work in progress on the K8S side. They are starting a work group on this AFAIK. so no instructions yet. The prow config has quite some references to master, especially for container images. They'll need to be changed once all the new images are created. We will also need to change all container images references in all repos (in hack and deploy/config folders).
Jenkins will also need to be reconfigured, that's something that we will take care of when the branch change is done.

I would propose to proceed the following way for the branch renaming :
- create the `main` branch in all repositories
- modify all references to master, in CI and in all repos, specifically for container images
- modify the default branch
- Fix CI and Jenkins
- remove master branch

**Comment by dhellmann** [comment]
We may also need to follow the instructions for setting the new default branch. https://docs.github.com/en/github/administering-a-repository/setting-the-default-branch

**Comment by dhellmann** [comment]
There is some additional guidance on https://github.com/github/renaming suggesting that if we wait a little bit, GitHub will provide better tools to make the transition go more smoothly.

**Comment by fmuyassarov** [comment]
It seems that Github has made it easy now to rename the existing branch: https://github.com/github/renaming. Based on that document, the list of the things that will be taken care by Github while renaming is:

1. Re-target any open pull requests
2. Update any draft releases based on the branch
3. Move any branch protection rules that explicitly reference the old name
4. Update the branch used to build GitHub Pages, if applicable
5. Show a notice to repository contributors, maintainers, and admins on the repository homepage with instructions to update local copies of the repository
6. Show a notice to contributors who git push to the old branch
7. Redirect web requests for the old branch name to the new branch name
8. Return a "Moved Permanently" response in API requests for the old branch name

**Comment by maelk** [comment]
This could be tried on a repo that is not much used, such as IPAM ?
