### ISSUE TITLE
Proposal: In-Place Executors

### ISSUE THREAD

**Issue by Arvinderpal** [metal3-io/metal3-docs#136]
For day-2 operations, users may want to make in-place changes to various host configurations. The configuration changes are in-place in the sense that they can be carried out without host reprovisioning or reboot. 

This proposal seeks to extend the Metal3MachineTemplate with a new CRD for storing the in-place host configuration data. In particular, it seeks to (i) add the ability to lookup the set of machines built from a specific Metal3MachineTemplate, and (ii) when the in-place host configuration data is updated by the user, pass this data, along with the set of machines impacted, to the in-place executors. 

https://docs.google.com/document/d/1Ozby8U08WIor1xkqXTDVMyjRUpdGUArKOZTgNOQAOn4/edit?usp=sharing 

NOTE: I'm keeping the proposal in google docs to allow for quicker iteration. I will move it into the /design section once we're close to the final design.

**Comment by maelk** [comment]
thank you for the proposal, it looks like a nice way to achieve the mutability you've been after. However, I wonder if that is something that would rather have its place at cluster API level, considering that this could apply independently of the provider, and you could pretty much replace the Metal3 words in this proposal by CAPI.

**Comment by Arvinderpal** [comment]
You're right that the approach described in this proposal is not metal3 specific and can be adapted by any other infrastructure provider. It may be worth asking the Cluster API community if they can make in-place executor templates first-class citizens much like MachineDeployments, etc. However, given that Machine Templates are themselves infrastructure provider specific, making an exception for in-place executors seems highly unlikely. 
There may be other ways of course. I'll forward this proposal to some people within the CAPI community who have expressed interest in in-place changes.

**Comment by maelk** [comment]
If this goes to CAPI, then I think we could put it at the KCP or at the machine deployment level. It would then be agnostic of the provider used.
