### ISSUE TITLE
FAQ link in README goes to blog

### ISSUE THREAD

**Issue by danwinship** [metal3-io/metal3-docs#175]
README.md has:

```
## Useful links

* [Quick start](http://metal3.io/try-it.html)
* [Demos](https://www.youtube.com/watch?v=VFbIHc3NbJo&list=PL2h5ikWC8viKmhbXHo1epPelGdCkVlF16&ab_channel=Metal3)
* [Blog posts](https://metal3.io/blog/index.html)
* [FAQ](https://metal3.io/blog/index.html)
```

Note that the "Blog posts" and "FAQ" links both go to the blog

**Comment by furkatgofurov7** [comment]
@danwinship thanks for the issue, the FAQ page link was incorrect and was removed as part of the #260. So, I am not reopening the issue, however, if you find any issues with that please feel free to reopen it.
