### ISSUE TITLE
User-guide: add introduction document for CAPM3

### ISSUE THREAD

**Issue by fmuyassarov** [metal3-io/metal3-docs#215]
Write down below sections for the Introduction section to CAPM3 section in the user-guide book. 
Describe:
- What is CAPM3
- Why and when should/can it be used
- It is relationship with CAPI

/kind documentation
/help wanted

**Comment by furkatgofurov7** [comment]
This is fixed in https://github.com/metal3-io/metal3-docs/pull/280

/close
