### ISSUE TITLE
User-guide: add document to briefly describe Pivoting feature in CAPM3

### ISSUE THREAD

**Issue by fmuyassarov** [metal3-io/metal3-docs#217]
Add a document briefly explaining the pivoting feature in CAPM3 and it is requirements.
Describe
- briefly Pivoting feature in CAPM3
- why we need it
- how to use it
- what are the caveats if any

/kind documentation
/help

**Comment by furkatgofurov7** [comment]
This is fixed in https://github.com/metal3-io/metal3-docs/pull/254

/close
