### ISSUE TITLE
User-guide: add doc to briefly describe Remediation feature in CAPM3

### ISSUE THREAD

**Issue by fmuyassarov** [metal3-io/metal3-docs#219]
Add a document briefly explaining the Remediation feature in CAPM3.
Describe:
- briefly Remediation feature in CAPM3
- why we need it
- how to use it
- what are the caveats if any

/kind documentation
/help

**Comment by macaptain** [comment]
I spent some time learning about this not so long ago, so I can try and write some documentation on this feature.

/assign

**Comment by macaptain** [comment]
Unfortunately, I won't have time to finish this.

/unassign

Relevant background for this documentation:

* Original proposal: https://github.com/metal3-io/metal3-docs/blob/main/design/cluster-api-provider-metal3/capm3-remediation-controller-proposal.md
* More interesting background details: https://github.com/metal3-io/cluster-api-provider-metal3/issues/392
* Ansible feature test showing the fields used for configuration of the feature and the expected resources that get created by the controller:
  * https://github.com/metal3-io/metal3-dev-env/blob/master/vm-setup/roles/v1aX_integration_test/templates/machine-healthcheck-worker.yaml
  * https://github.com/metal3-io/metal3-dev-env/blob/master/vm-setup/roles/v1aX_integration_test/tasks/healthcheck.yml

**Comment by Rozzii** [comment]
Thanks @smoshiur1237 
/remove-help
