### ISSUE TITLE
User-guide: Add introduction doc to Ironic in Metal3

### ISSUE THREAD

**Issue by fmuyassarov** [metal3-io/metal3-docs#230]
Describe:

- What is ironic
- Why Metal3 uses Ironic
- How Metal3 uses Ironic
- What are the limitations of Ironic in Metal3
/kind documentation
/help

/cc @dtantsur @Rozzii

**Comment by elfosardo** [comment]
/assign
I guess I can help with this too :)

**Comment by fmuyassarov** [comment]
Thank you @elfosardo
