### ISSUE TITLE
Should have a quick start guide to kick the tire

### ISSUE THREAD

**Issue by gangchen03** [metal3-io/metal3-docs#25]
looking for a getting-started guide to get a cluster provisioned using Metalkube. Can't find it anywhere. Wouldn't mind submit a PR for one once I figured out how to get the code to work.

**Comment by russellb** [comment]
sorry I missed this issue.  I've been working on a dev env here:  https://github.com/metal3-io/metal3-dev-env

Is this the kind of thing you're looking for?

**Comment by russellb** [comment]
Let me know if you have any feedback on metal3-dev-env.  Thanks!
