### ISSUE TITLE
User-guide: migrate configuration docs from BMO

### ISSUE THREAD

**Issue by dtantsur** [metal3-io/metal3-docs#316]
We need to have user-facing content in the user guide. The configuration should be a part of the installation guide, i.e. the missing "Install Baremetal Operator" page from https://book.metal3.io/bmo/introduction.html

Migrate from https://github.com/metal3-io/baremetal-operator/blob/main/docs/configuration.md
https://github.com/metal3-io/baremetal-operator/blob/main/docs/ironic-authentication.md
and https://github.com/metal3-io/baremetal-operator/blob/main/docs/deploying.md

/kind documentation
/triage accepted
/help

**Comment by adithyaakrishna** [comment]
@dtantsur Can I take this up?

**Comment by dtantsur** [comment]
@adithyaakrishna absolutely, unassigned bugs with "help wanted" are free to take.

**Comment by wrkode** [comment]
@dtantsur, I'm working on this issue, I already have a local environment and I'm working on the Install page.
Do I understand correctly that the desire is to have the Install Baremetal Page, hosting the full content of:
configuration.md
ironic-authentication.md
deploying.md

With the appropriate discursive continuity?

disclaimer: this is my first contribution, so please be patient :)

**Comment by wrkode** [comment]
@dtantsur I believe this issue can be closed as #352 got merged.

**Comment by Rozzii** [comment]
@dtantsur  Are you fine with the current state of the docs , do we need to move anything else around or can we close this ?

**Comment by dtantsur** [comment]
I believe we should remove the docs from the BMO repo now so that they don't diverge. Any objections?

**Comment by Rozzii** [comment]
> I believe we should remove the docs from the BMO repo now so that they don't diverge. Any objections?
No Objections I am happy to do it.

**Comment by Rozzii** [comment]
/remove-lifecycle stale
I have to check this not sure about the status

**Comment by wrkode** [comment]
> /remove-lifecycle stale I have to check this not sure about the status

@Rozzii, I've completed this via #352 which got merged, but the issue was never closed

**Comment by Rozzii** [comment]
thanks @wrkode , then I will close this ticket
