### ISSUE TITLE
A lot of broken links in metal3-docs

### ISSUE THREAD

**Issue by tuminoid** [metal3-io/metal3-docs#328]
This is the current list of broken links in this repository that need to be fixed.

```console
 + find . -name '*.md' -not -path './node_modules/*' -exec markdown-link-check '{}' --config .markdownlinkcheck.json -q ';'
| + set +x
| =========================> MARKDOWN LINK CHECK <=========================
| 
| FILE: ./docs/presentations/README.md
| 
| 4 links checked.
| 
| FILE: ./docs/README.md
| 
| 2 links checked.
| 
| FILE: ./docs/prerequisites.md
| 
| 0 links checked.
| 
| FILE: ./docs/user-guide/README.md
| 
| 5 links checked.
| 
| FILE: ./docs/user-guide/src/introduction.md
| 
| 7 links checked.
| 
| FILE: ./docs/user-guide/src/ipam/ipam_installation.md
| 
| 4 links checked.
| 
| FILE: ./docs/user-guide/src/ipam/introduction.md
| 
| 1 links checked.
| 
| FILE: ./docs/user-guide/src/version_support.md
| 
| 1 links checked.
| 
| FILE: ./docs/user-guide/src/security_policy.md
| 
| 4 links checked.
| 
| FILE: ./docs/user-guide/src/flake/introduction.md
| 
| 0 links checked.
| 
| FILE: ./docs/user-guide/src/flake/bmh_stuck.md
| [✖] https://opendev.org/openstack/ironic/src/commit/eeeaa274cfc7ebee52beaed97571e2f87127f2dd/ironic/db/sqlalchemy/api.py#L2056
| 
| 3 links checked.
| 
| ERROR: 1 dead links found!
| [✖] https://opendev.org/openstack/ironic/src/commit/eeeaa274cfc7ebee52beaed97571e2f87127f2dd/ironic/db/sqlalchemy/api.py#L2056 → Status: 0
| 
| FILE: ./docs/user-guide/src/flake/calico_manifest_download.md
| 
| 1 links checked.
| 
| FILE: ./docs/user-guide/src/flake/floating_ip_error.md
| 
| 0 links checked.
| 
| FILE: ./docs/user-guide/src/flake/prow.md
| 
| 1 links checked.
| 
| FILE: ./docs/user-guide/src/flake/nordix_timeout.md
| 
| 3 links checked.
| 
| FILE: ./docs/user-guide/src/SUMMARY.md
| 
| 31 links checked.
| 
| FILE: ./docs/user-guide/src/ironic/ironic_installation.md
| 
| 4 links checked.
| 
| FILE: ./docs/user-guide/src/ironic/introduction.md
| 
| 9 links checked.
| 
| FILE: ./docs/user-guide/src/ironic/ironic_variables.md
| 
| 0 links checked.
| 
| FILE: ./docs/user-guide/src/ironic/ironic-container-images.md
| 
| 5 links checked.
| 
| FILE: ./docs/user-guide/src/ironic/ironic-python-agent.md
| 
| 5 links checked.
| 
| FILE: ./docs/user-guide/src/capm3/node_reuse.md
| 
| 2 links checked.
| 
| FILE: ./docs/user-guide/src/capm3/introduction.md
| 
| 14 links checked.
| 
| FILE: ./docs/user-guide/src/capm3/remediaton.md
| 
| 3 links checked.
| 
| FILE: ./docs/user-guide/src/capm3/installation_guide.md
| [✖] TODO
| 
| 4 links checked.
| 
| ERROR: 1 dead links found!
| [✖] TODO → Status: 400
| 
| FILE: ./docs/user-guide/src/capm3/automated_cleaning.md
| 
| 2 links checked.
| 
| FILE: ./docs/user-guide/src/capm3/pivoting.md
| 
| 4 links checked.
| 
| FILE: ./docs/user-guide/src/bmo/automatic_secure_boot.md
| 
| 2 links checked.
| 
| FILE: ./docs/user-guide/src/bmo/reboot_annotation.md
| 
| 2 links checked.
| 
| FILE: ./docs/user-guide/src/bmo/detached_annotation.md
| 
| 2 links checked.
| 
| FILE: ./docs/user-guide/src/bmo/introduction.md
| 
| 2 links checked.
| 
| FILE: ./docs/user-guide/src/bmo/status_annotation.md
| 
| 1 links checked.
| 
| FILE: ./docs/user-guide/src/bmo/automated_cleaning.md
| 
| 3 links checked.
| 
| FILE: ./docs/user-guide/src/bmo/external_inspection.md
| 
| 1 links checked.
| 
| FILE: ./docs/user-guide/src/bmo/live-iso.md
| 
| 2 links checked.
| 
| FILE: ./docs/user-guide/src/bmo/inspect_annotation.md
| 
| 1 links checked.
| 
| FILE: ./design/_template.md
| [✖] /designs/_template.md
| 
| 2 links checked.
| 
| ERROR: 1 dead links found!
| [✖] /designs/_template.md → Status: 400
| 
| FILE: ./design/baremetal-operator/host-config-drive.md
| 
| 3 links checked.
| 
| FILE: ./design/baremetal-operator/managing-provisioning-dependencies.md
| 
| 1 links checked.
| 
| FILE: ./design/baremetal-operator/annotation-for-power-cycling-and-deleting-failed-nodes.md
| 
| 5 links checked.
| 
| FILE: ./design/baremetal-operator/bmo-part-of-capm3.md
| 
| 1 links checked.
| 
| FILE: ./design/baremetal-operator/reboot-interface.md
| 
| 0 links checked.
| 
| FILE: ./design/baremetal-operator/bmc-events.md
| [✖] https://www.dell.com/support/manuals/en-jm/idrac9-lifecycle-controller-v4.x-series/idrac9_4.00.00.00_redfishapiguide_pub/temperature?guid=guid-5a798111-407b-485d-b6fb-7d6e367d4ad4&lang=en-us
| 
| 7 links checked.
| 
| ERROR: 1 dead links found!
| [✖] https://www.dell.com/support/manuals/en-jm/idrac9-lifecycle-controller-v4.x-series/idrac9_4.00.00.00_redfishapiguide_pub/temperature?guid=guid-5a798111-407b-485d-b6fb-7d6e367d4ad4&lang=en-us → Status: 403
| 
| FILE: ./design/baremetal-operator/explicit-boot-mode.md
| 
| 4 links checked.
| 
| FILE: ./design/baremetal-operator/bulk-set-bios-config.md
| 
| 7 links checked.
| 
| FILE: ./design/baremetal-operator/sub-states.md
| 
| 2 links checked.
| 
| FILE: ./design/baremetal-operator/hardwaredata_crd.md
| 
| 13 links checked.
| 
| FILE: ./design/baremetal-operator/bmc-address.md
| 
| 1 links checked.
| 
| FILE: ./design/baremetal-operator/raid-disk-controller.md
| 
| 0 links checked.
| 
| FILE: ./design/baremetal-operator/bmh_live_iso.md
| 
| 6 links checked.
| 
| FILE: ./design/baremetal-operator/deploy-steps.md
| 
| 6 links checked.
| 
| FILE: ./design/baremetal-operator/kubebuilder-migration.md
| [✖] https://sdk.operatorframework.io/docs/building-operators/golang/project_migration_guide/
| 
| 16 links checked.
| 
| ERROR: 1 dead links found!
| [✖] https://sdk.operatorframework.io/docs/building-operators/golang/project_migration_guide/ → Status: 404
| 
| FILE: ./design/baremetal-operator/limit-hosts-provisioning.md
| 
| 2 links checked.
| 
| FILE: ./design/baremetal-operator/external-introspection.md
| 
| 6 links checked.
| 
| FILE: ./design/baremetal-operator/how-ironic-works.md
| 
| 6 links checked.
| 
| FILE: ./design/baremetal-operator/secure-boot.md
| 
| 2 links checked.
| 
| FILE: ./design/baremetal-operator/image-builder-integration.md
| 
| 3 links checked.
| 
| FILE: ./design/baremetal-operator/user-defined-root-device-hints.md
| 
| 2 links checked.
| 
| FILE: ./design/baremetal-operator/remove-host.md
| 
| 0 links checked.
| 
| FILE: ./design/baremetal-operator/unmanaged-state.md
| 
| 2 links checked.
| 
| FILE: ./design/baremetal-operator/raid-api.md
| 
| 2 links checked.
| 
| FILE: ./design/baremetal-operator/inspection-api.md
| 
| 2 links checked.
| 
| FILE: ./design/baremetal-operator/implicit-boot-mode.md
| [✖] https://github.com/metal3-io/baremetal-operator/blob/main/pkg/bmc/access.go#L27
| 
| 8 links checked.
| 
| ERROR: 1 dead links found!
| [✖] https://github.com/metal3-io/baremetal-operator/blob/main/pkg/bmc/access.go#L27 → Status: 404
| 
| FILE: ./design/baremetal-operator/hardware-status.md
| 
| 6 links checked.
| 
| FILE: ./design/baremetal-operator/detached-annotation.md
| 
| 4 links checked.
| 
| FILE: ./design/baremetal-operator/bios-config.md
| 
| 3 links checked.
| 
| FILE: ./design/helm-charts/single-pod-helm-chart.md
| 
| 0 links checked.
| 
| FILE: ./design/image-ownership.md
| 
| 0 links checked.
| 
| FILE: ./design/api-design-principles.md
| 
| 1 links checked.
| 
| FILE: ./design/physical-network-api-prototype.md
| 
| 8 links checked.
| 
| FILE: ./design/ip-address-manager/ip-address-management-for-networkdata.md
| 
| 23 links checked.
| 
| FILE: ./design/nodes-machines-and-hosts.md
| [✖] https://kubernetes-sigs.github.io/cluster-api/common_code/machine_controller.html
| 
| 8 links checked.
| 
| ERROR: 1 dead links found!
| [✖] https://kubernetes-sigs.github.io/cluster-api/common_code/machine_controller.html → Status: 404
| 
| FILE: ./design/metadata-handling.md
| 
| 3 links checked.
| 
| FILE: ./design/fd-support-kcp.md
| 
| 7 links checked.
| 
| FILE: ./design/ironic_authentication.md
| 
| 4 links checked.
| 
| FILE: ./design/bare-metal-style-guide.md
| 
| 0 links checked.
| 
| FILE: ./design/sync-labels-bmh-to-node.md
| [✖] https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/0000-20170814-bounding-self-labeling-kubelets.md
| 
| 3 links checked.
| 
| ERROR: 1 dead links found!
| [✖] https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/0000-20170814-bounding-self-labeling-kubelets.md → Status: 404
| 
| FILE: ./design/use-ironic.md
| 
| 4 links checked.
| 
| FILE: ./design/ironic-debuggability-improvement.md
| [✖] https://github.com/metal3-io/baremetal-operator/blob/main/ironic-deployment/ironic/ironic.yaml
| 
| 5 links checked.
| 
| ERROR: 1 dead links found!
| [✖] https://github.com/metal3-io/baremetal-operator/blob/main/ironic-deployment/ironic/ironic.yaml → Status: 404
| 
| FILE: ./design/hardware-classification-controller/expected-hardware-configuration-validation.md
| [✖] https://github.com/metal3-io/baremetal-operator/blob/main/deploy/crds/metal3.io_baremetalhosts_crd.yaml
| 
| 4 links checked.
| 
| ERROR: 1 dead links found!
| [✖] https://github.com/metal3-io/baremetal-operator/blob/main/deploy/crds/metal3.io_baremetalhosts_crd.yaml → Status: 404
| 
| FILE: ./design/hardware-classification-controller/support-for-new-parameters-hwcc-DiskAndNIC.md
| 
| 4 links checked.
| 
| FILE: ./design/hardware-classification-controller/support-for-error-count-parameter-hwcc.md
| 
| 3 links checked.
| 
| FILE: ./design/hardware-classification-controller/support-for-new-parameters-hwcc.md
| 
| 4 links checked.
| 
| FILE: ./design/reproducible-metal3-dev-env.md
| 
| 2 links checked.
| 
| FILE: ./design/cluster-api-provider-metal3/node_reuse.md
| [✖] https://github.com/metal3-io/metal3-docs/blob/main/design/capm3-remediation-controller-proposal.md
| 
| 2 links checked.
| 
| ERROR: 1 dead links found!
| [✖] https://github.com/metal3-io/metal3-docs/blob/main/design/capm3-remediation-controller-proposal.md → Status: 404
| 
| FILE: ./design/cluster-api-provider-metal3/capm3-remediation-controller-proposal.md
| [✖] https://cluster-api.sigs.k8s.io/tasks/healthcheck.html
| [✖] https://github.com/metal3-io/metal3-docs/blob/main/design/baremetal-operator/re-introspection-interface.md
| 
| 5 links checked.
| 
| ERROR: 2 dead links found!
| [✖] https://cluster-api.sigs.k8s.io/tasks/healthcheck.html → Status: 404
| [✖] https://github.com/metal3-io/metal3-docs/blob/main/design/baremetal-operator/re-introspection-interface.md → Status: 404
| 
| FILE: ./design/cluster-api-provider-metal3/capm3-remediation-controller-improvement-proposal.md
| 
| 7 links checked.
| 
| FILE: ./design/cluster-api-provider-metal3/allow_disabling_node_disk_cleaning.md
| 
| 5 links checked.
| 
| FILE: ./design/community/foundation-proposal.md
| [✖] https://github.com/cncf/toc/blob/master/process/project_proposals.adoc
| [✖] https://github.com/cncf/toc/blob/master/process/graduation_criteria.adoc
| 
| 8 links checked.
| 
| ERROR: 2 dead links found!
| [✖] https://github.com/cncf/toc/blob/master/process/project_proposals.adoc → Status: 404
| [✖] https://github.com/cncf/toc/blob/master/process/graduation_criteria.adoc → Status: 404
| 
| FILE: ./design/community/book-proposal.md
| 
| 5 links checked.
| 
| FILE: ./ADOPTERS.md
| [✖] https://www.ericsson.com/en/portfolio/digital-services/cloud-infrastructure/cloud-container-distribution
| 
| 4 links checked.
| 
| ERROR: 1 dead links found!
| [✖] https://www.ericsson.com/en/portfolio/digital-services/cloud-infrastructure/cloud-container-distribution → Status: 403
| 
| FILE: ./processes/managing-reviewers.md
| 
| 3 links checked.
| 
| FILE: ./processes/reviewer-permissions-migration.md
| 
| 2 links checked.
| 
| FILE: ./processes/roadmap.md
| 
| 1 links checked.
| 
| FILE: ./processes/triage.md
| [✖] https://github.com/issues?utf8=%E2%9C%93&q=archived%3Afalse+user%3Ametal3-io+no%3Alabel+is%3Aissue+sort%3Acreated-asc+is%3Aopen
| [✖] https://github.com/issues?utf8=%E2%9C%93&q=archived%3Afalse+user%3Ametal3-io+is%3Aissue+sort%3Acreated-asc+is%3Aopen+label%3Apriority%2Fawaiting-more-evidence
| [✖] https://github.com/issues?q=archived%3Afalse+user%3Ametal3-io+is%3Aissue+sort%3Acreated-asc+is%3Aopen+label%3Alifecycle%2Fstale
| 
| 3 links checked.
| 
| ERROR: 3 dead links found!
| [✖] https://github.com/issues?utf8=%E2%9C%93&q=archived%3Afalse+user%3Ametal3-io+no%3Alabel+is%3Aissue+sort%3Acreated-asc+is%3Aopen → Status: 404
| [✖] https://github.com/issues?utf8=%E2%9C%93&q=archived%3Afalse+user%3Ametal3-io+is%3Aissue+sort%3Acreated-asc+is%3Aopen+label%3Apriority%2Fawaiting-more-evidence → Status: 404
| [✖] https://github.com/issues?q=archived%3Afalse+user%3Ametal3-io+is%3Aissue+sort%3Acreated-asc+is%3Aopen+label%3Alifecycle%2Fstale → Status: 404
| 
| FILE: ./CONTRIBUTING.md
| 
| 2 links checked.
| 
| FILE: ./CODE_OF_CONDUCT.md
| 
| 5 links checked.
| 
| FILE: ./README.md
| 
| 11 links checked.
| 
| FILE: ./maintainers/README.md
| 
| 0 links checked.
| 
| FILE: ./crs_reference.md
| [✖] https://github.com/metal3-io/metal3-dev-env/tree/master/crs
| 
| 3 links checked.
| 
| ERROR: 1 dead links found!
| [✖] https://github.com/metal3-io/metal3-dev-env/tree/master/crs → Status: 404
| 
```

After these are fixed, we can merge https://github.com/metal3-io/metal3-docs/pull/322 to add broken link checker to keep repository clean from broken links.

**Comment by elfosardo** [comment]
@tuminoid thanks for this!
Let's keep this open for our outreachy intern if possible, they should start next week

**Comment by ayushkcs** [comment]
Hello @tuminoid,
I am new to this community and open source, too. Can I try to fix this?

**Comment by ashutosh887** [comment]
@elfosardo @tuminoid 
I would like to take this

**Comment by tuminoid** [comment]
> @tuminoid can we please assign this to @SafeEHA ? thanks!

In GutHub, you can’t assign non-members or non-contributors that have not previously commented in an issue/PR. So please @SafeEHA comment here and we can assign this to you.

**Comment by SafeEHA** [comment]
Hello, 
I would begin working on this as soon as possible
Thanks

**Comment by ashutosh887** [comment]
I am also willing to work on the issue @tuminoid @elfosardo 

cc:
https://github.com/metal3-io/metal3-docs/issues/328#issuecomment-1531843191

**Comment by SafeEHA** [comment]
Hello @dhellmann 
Please can you give me the correct link for the hyperlink [here](https://github.com/metal3-io/metal3-docs/blob/main/designs/_template.md)  on [this](https://github.com/metal3-io/metal3-docs/blob/main/design/_template.md) page

**Comment by dhellmann** [comment]
> Hello @dhellmann
> Please can you give me the correct link for the hyperlink [here](https://github.com/metal3-io/metal3-docs/blob/main/designs/_template.md) on [this](https://github.com/metal3-io/metal3-docs/blob/main/design/_template.md) page

It looks like that template is trying to link to itself and I either typoed "design" as "designs" or things were moved later. So I think if you change `https://github.com/metal3-io/metal3-docs/blob/main/designs/_template.md` to `https://github.com/metal3-io/metal3-docs/blob/main/design/_template.md` it will work.

**Comment by SafeEHA** [comment]
Hello @dhellmann 
Please can you give me the correct link for 
[operator-sdk 1.0 migration guide](https://sdk.operatorframework.io/docs/building-operators/golang/project_migration_guide/ ), on [this](https://github.com/metal3-io/metal3-docs/blob/main/design/baremetal-operator/kubebuilder-migration.md ) page
[AccessDetails interface](https://github.com/metal3-io/baremetal-operator/blob/main/pkg/bmc/access.go#L27) on [this](https://github.com/metal3-io/metal3-docs/blob/main/design/baremetal-operator/implicit-boot-mode.md) page
And [Machine](https://kubernetes-sigs.github.io/cluster-api/common_code/machine_controller.html ) on [this](https://github.com/metal3-io/metal3-docs/blob/main/design/nodes-machines-and-hosts.md ) page

**Comment by SafeEHA** [comment]
Hi @kashifest 
Please can you help provide the correct links to [metal3 spec for bare-metal](https://github.com/metal3-io/baremetal-operator/blob/main/deploy/crds/metal3.io_baremetalhosts_crd.yaml) on this [page](https://github.com/metal3-io/metal3-docs/blob/main/design/ironic-debuggability-improvement.md) 
[Remediation](https://github.com/metal3-io/metal3-docs/blob/main/design/capm3-remediation-controller-proposal.md) on this [page](https://github.com/metal3-io/metal3-docs/blob/main/design/cluster-api-provider-metal3/node_reuse.md)

https://github.com/metal3-io/baremetal-operator/blob/main/deploy/crds/metal3.io_baremetalhosts_crd.yaml on this [page](https://github.com/metal3-io/metal3-docs/blob/main/design/ironic-debuggability-improvement.md )

[re-inspection API proposal](https://github.com/metal3-io/metal3-docs/blob/main/design/baremetal-operator/re-introspection-interface.md) and [CAPI MachineHealthCheck](https://cluster-api.sigs.k8s.io/tasks/healthcheck.html) on this [page](https://github.com/metal3-io/metal3-docs/blob/main/design/cluster-api-provider-metal3/capm3-remediation-controller-proposal.md 
)

**Comment by SafeEHA** [comment]
Hi @fmuyassarov 
Please can you provide the correct links to these 
[Link](https://www.ericsson.com/en/portfolio/cloud-software--services/cloud-infrastructure/cloud-container-distribution) on this [page]( https://github.com/metal3-io/metal3-docs/blob/main/ADOPTERS.md )

Hello @Hellcatlk 
Please can you provide the correct link for [GitHub Search Query](https://github.com/issues?utf8=%E2%9C%93&q=archived%3Afalse+user%3Ametal3-io+no%3Alabel+is%3Aissue+sort%3Acreated-asc+is%3Aopen) Under New Issue Triage on this [page](https://github.com/metal3-io/metal3-docs/blob/main/processes/triage.md )

Hello @Arvinderpal 
Please can you provide the correct link to [Addressed](https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/0000-20170814-bounding-self-labeling-kubelets.md ) on this [page](https://github.com/metal3-io/metal3-docs/blob/main/design/sync-labels-bmh-to-node.md)

**Comment by SafeEHA** [comment]
Hello @fmuyassarov @Hellcatlk  @dhellmann @Arvinderpal @kashifest 
Please I need your help with these broken links

**Comment by kashifest** [comment]
> Hello @fmuyassarov @Hellcatlk @dhellmann @Arvinderpal @kashifest Please I need your help with these broken links

I will provide the links soon.

**Comment by SafeEHA** [comment]
Hello Everyone 
So far, I have made a partial fix for some of the broken links and created #333

**Comment by tuminoid** [comment]
It has been a month since last update. How is this progressing?

**Comment by kashifest** [comment]
> page

CAPI machine healthcheck - https://cluster-api.sigs.k8s.io/developer/architecture/controllers/machine-health-check.html

**Comment by SafeEHA** [comment]
Thank you @kashifest 
I would effect these changes and create a PR

**Comment by SafeEHA** [comment]
@kashifest 
I also forgot to add that I need the correct link for https://github.com/metal3-io/baremetal-operator/blob/main/ironic-deployment/ironic/ironic.yaml under Design Details on https://github.com/metal3-io/metal3-docs/blob/main/design/ironic-debuggability-improvement.md page.

**Comment by tuminoid** [comment]
> HI @tuminoid I'm making progress on it, once I'm able to get all the correct links PRs would be created respectively

I'd like to see a bit more proactive work on it, by trying to identify the correct URL to best of your ability, and creating PR with those, and then address the feedback if the reviewer's say you got the link wrong.

**Comment by kashifest** [comment]
> @kashifest I also forgot to add that I need the correct link for https://github.com/metal3-io/baremetal-operator/blob/main/ironic-deployment/ironic/ironic.yaml under Design Details on https://github.com/metal3-io/metal3-docs/blob/main/design/ironic-debuggability-improvement.md page.

here you go, https://github.com/metal3-io/baremetal-operator/blob/dabe5e14bafa00db6ccb37f1169c74ee3dac4425/ironic-deployment/base/ironic.yaml, note that I have given the perma link here. Please obtain the permalink of the links I have provided earlier so that the links dont ront even if the file changes in future.

**Comment by SafeEHA** [comment]
@tuminoid 
I apologize for how long this has taken, I am still quite new here and I've been trying to get familiar with everything 
I corrected the links for the first 2 out of the 3 broken links in the first PR I created, the others have been a bit more complicated to decipher but i assure you I'm doing my best

**Comment by tuminoid** [comment]
> Hello, please I need to have my access to the repo updated I can't seem to push updates

You need to push the branches to your fork, and then create PR. Directly pushing is not allowed for anyone.

**Comment by SafeEHA** [comment]
Hello,
So far, I have created PRs #336 #333 fixing the broken links that had wrong paths or some other issue with some help and within how much I know currently, I have these left 
- [operator-sdk 1.0 migration guide](https://sdk.operatorframework.io/docs/building-operators/golang/project_migration_guide/ ), on [this](https://github.com/metal3-io/metal3-docs/blob/main/design/baremetal-operator/kubebuilder-migration.md ) page
- [Machine](https://kubernetes-sigs.github.io/cluster-api/common_code/machine_controller.html ) on [this](https://github.com/metal3-io/metal3-docs/blob/main/design/nodes-machines-and-hosts.md ) page 
- [GitHub Search Query](https://github.com/issues?utf8=%E2%9C%93&q=archived%3Afalse+user%3Ametal3-io+no%3Alabel+is%3Aissue+sort%3Acreated-asc+is%3Aopen) under New issue triage on [this](https://github.com/metal3-io/metal3-docs/blob/main/processes/triage.md) page 
- [CRs](https://github.com/metal3-io/metal3-dev-env/tree/master/crs) on this [page](https://github.com/metal3-io/metal3-docs/blob/main/crs_reference.md )
- [Link](https://www.ericsson.com/en/portfolio/cloud-software--services/cloud-infrastructure/cloud-container-distribution) on this [page]( https://github.com/metal3-io/metal3-docs/blob/main/ADOPTERS.md )
-  [Addressed](https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/0000-20170814-bounding-self-labeling-kubelets.md ) on this [page](https://github.com/metal3-io/metal3-docs/blob/main/design/sync-labels-bmh-to-node.md)

 Please I need help getting the correct links for these as would really like to close out this issue as soon as possible with your help

**Comment by tuminoid** [comment]
@huutomerkki if you're interested, you could work with @SafeEHA to get all of the links fixed. It has been pending quite a while.

**Comment by Gutopro** [comment]
hello everyone, I'm Nicholas a software developer from Nigeria who is new to open source. I was going through the metal3 user-guide and I came across a broken link, looking at the repo I've seen that this is a good first issue and I'd be more than willing to help, could you kindly bring me up to speed on what to do and how to go about it? thank you and hope to hear from you.

**Comment by tuminoid** [comment]
> hello everyone, I'm Nicholas a software developer from Nigeria who is new to open source. I was going through the metal3 user-guide and I came across a broken link, looking at the repo I've seen that this is a good first issue and I'd be more than willing to help, could you kindly bring me up to speed on what to do and how to go about it? thank you and hope to hear from you.

Hello @Gutopro. To contribute to Metal3, we follow Github PR workflow described here: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
Also see https://github.com/metal3-io/metal3-docs/blob/main/CONTRIBUTING.md

If you encounter a broken link (or fix a broken link identified in this link), you'd need to find a working link and then submit a PR to replace the broken link with a working one. It will then be reviewed by project members and eventually merged, if it fixed the issue.

**Comment by Gutopro** [comment]
thanks @tuminoid I'll start working on it immediately.

**Comment by lentzi90** [comment]
Adding some suggestions and hints inline

> Hello, So far, I have created PRs #336 #333 fixing the broken links that had wrong paths or some other issue with some help and within how much I know currently, I have these left
> 
>     * [operator-sdk 1.0 migration guide](https://sdk.operatorframework.io/docs/building-operators/golang/project_migration_guide/), on [this](https://github.com/metal3-io/metal3-docs/blob/main/design/baremetal-operator/kubebuilder-migration.md) page

I think we should link [here](https://sdk.operatorframework.io/docs/building-operators/golang/migration/)

>     * [Machine](https://kubernetes-sigs.github.io/cluster-api/common_code/machine_controller.html) on [this](https://github.com/metal3-io/metal3-docs/blob/main/design/nodes-machines-and-hosts.md) page

Find some kind of definition or API reference [here](https://cluster-api.sigs.k8s.io/) and link to it.

>     * [GitHub Search Query](https://github.com/issues?utf8=%E2%9C%93&q=archived%3Afalse+user%3Ametal3-io+no%3Alabel+is%3Aissue+sort%3Acreated-asc+is%3Aopen) under New issue triage on [this](https://github.com/metal3-io/metal3-docs/blob/main/processes/triage.md) page

Looks to me like this link is working.

>     * [CRs](https://github.com/metal3-io/metal3-dev-env/tree/master/crs) on this [page](https://github.com/metal3-io/metal3-docs/blob/main/crs_reference.md)

Check when this page in the docs was first written and go back in history to the same point in metal3-dev-env. Check what the content was back then and either link to that point in time or find some new material that matches.

>     * [Link](https://www.ericsson.com/en/portfolio/cloud-software--services/cloud-infrastructure/cloud-container-distribution) on this [page](https://github.com/metal3-io/metal3-docs/blob/main/ADOPTERS.md)

The page no longer exists. No change needed.

>     * [Addressed](https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/0000-20170814-bounding-self-labeling-kubelets.md) on this [page](https://github.com/metal3-io/metal3-docs/blob/main/design/sync-labels-bmh-to-node.md)

It has moved [here](https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/279-limit-node-access/README.md)

**Comment by lentzi90** [comment]
@SafeEHA do you want to work on this still? If not, I'm going to bring it to our contrib-fest session at KubeCon 🙂

**Comment by SafeEHA** [comment]
Yeah with your suggestions I should make some progress, I'll have updates soon

**Comment by SafeEHA** [comment]
So far I fixed 3 out of the 6 broken links I listed earlier on this PR #387 thanks to pointers from @lentzi90 
The other 3 however are still pending...
This - [GitHub Search Query](https://github.com/issues?utf8=%E2%9C%93&q=archived%3Afalse+user%3Ametal3-io+no%3Alabel+is%3Aissue+sort%3Acreated-asc+is%3Aopen) under New issue triage and this - [CRs](https://github.com/metal3-io/metal3-dev-env/tree/master/crs) on this [page](https://github.com/metal3-io/metal3-docs/blob/main/crs_reference.md )

Also, for this - [Link](https://www.ericsson.com/en/portfolio/cloud-software--services/cloud-infrastructure/cloud-container-distribution) on this [page]( https://github.com/metal3-io/metal3-docs/blob/main/ADOPTERS.md ), would we take it out completely or replace with some other resource since it no longer exists?

**Comment by lentzi90** [comment]
> This - [GitHub Search Query](https://github.com/issues?utf8=%E2%9C%93&q=archived%3Afalse+user%3Ametal3-io+no%3Alabel+is%3Aissue+sort%3Acreated-asc+is%3Aopen) under New issue triage and this - [CRs](https://github.com/metal3-io/metal3-dev-env/tree/master/crs) on this [page](https://github.com/metal3-io/metal3-docs/blob/main/crs_reference.md)

The GitHub Search Query works as it should but we may have to configure the link checker to understand it. Ignore it for now.

> [CRs](https://github.com/metal3-io/metal3-dev-env/tree/master/crs) on this [page](https://github.com/metal3-io/metal3-docs/blob/main/crs_reference.md)

As mentioned, check the [history](https://github.com/metal3-io/metal3-docs/commits/main/crs_reference.md) for the page. When was it created? Then go to [metal3-dev-env commits](https://github.com/metal3-io/metal3-dev-env/commits/main/) and select commits from around the same time. Pick a commit and click "Browse the repository at this time" (`< >`). Hopefully you should now see the `crs` folder.

Check what the content is. If we have something similar somewhere else, we can link to that. Otherwise just link to the the CRs at this commit.

> Also, for this - [Link](https://www.ericsson.com/en/portfolio/cloud-software--services/cloud-infrastructure/cloud-container-distribution) on this [page](https://github.com/metal3-io/metal3-docs/blob/main/ADOPTERS.md), would we take it out completely or replace with some other resource since it no longer exists?

It is already removed. You don't have to do anything.

**Comment by SafeEHA** [comment]
I followed your instructions and found [this](https://github.com/metal3-io/metal3-dev-env/tree/390fa5ad495c47aeb829b17edc2b40976e52cbea/crs/v1alpha2)
I remember going through the commits last time but maybe cause I was looking for a file CRs I didn't find anything, but the above link points to a sub-dir that leads to v1apha2 with a bunch of yaml files , I looked through, and didn't find anything like it in metal-docs repo.  I am not certain of the specific file from the list, please help point me to the right one
cc: @lentzi90

**Comment by SafeEHA** [comment]
> > This - [GitHub Search Query](https://github.com/issues?utf8=%E2%9C%93&q=archived%3Afalse+user%3Ametal3-io+no%3Alabel+is%3Aissue+sort%3Acreated-asc+is%3Aopen) under New issue triage and this - [CRs](https://github.com/metal3-io/metal3-dev-env/tree/master/crs) on this [page](https://github.com/metal3-io/metal3-docs/blob/main/crs_reference.md)
> 
> The GitHub Search Query works as it should but we may have to configure the link checker to understand it. Ignore it for now.
> 
> > [CRs](https://github.com/metal3-io/metal3-dev-env/tree/master/crs) on this [page](https://github.com/metal3-io/metal3-docs/blob/main/crs_reference.md)
> 
> As mentioned, check the [history](https://github.com/metal3-io/metal3-docs/commits/main/crs_reference.md) for the page. When was it created? Then go to [metal3-dev-env commits](https://github.com/metal3-io/metal3-dev-env/commits/main/) and select commits from around the same time. Pick a commit and click "Browse the repository at this time" (`< >`). Hopefully you should now see the `crs` folder.
> 
> Check what the content is. If we have something similar somewhere else, we can link to that. Otherwise just link to the the CRs at this commit.
> 
> > Also, for this - [Link](https://www.ericsson.com/en/portfolio/cloud-software--services/cloud-infrastructure/cloud-container-distribution) on this [page](https://github.com/metal3-io/metal3-docs/blob/main/ADOPTERS.md), would we take it out completely or replace with some other resource since it no longer exists?
> 
> It is already removed. You don't have to do anything.

Apologies for responding late, was a busy week
So, i followed your instructions and found [this](https://github.com/metal3-io/metal3-dev-env/tree/390fa5ad495c47aeb829b17edc2b40976e52cbea/crs/v1alpha2)
I remember going through the commits last time but maybe cause I was looking for a file CRs I didn't find anything, but the above link points to a sub-dir that leads to v1apha2 with a bunch of yaml files , I looked through, and didn't find anything like it in metal-docs repo.  I am not certain of the specific file from the list, please help point me to the right one

**Comment by lentzi90** [comment]
You can link directly to this: https://github.com/metal3-io/metal3-dev-env/tree/b5a53ecf9576c6deab81f692733782d4c5e8091a/crs
That is what they meant to link to originally.

**Comment by SafeEHA** [comment]
I've made the necessary changes to the PR, kindly review and I'll await your comments and hopefully we can go ahead to merge the broken link checker on #322 like @tuminoid mentioned in the beginning

**Comment by tuminoid** [comment]
/remove-lifecycle stale

I'm going to split this issue up, with the fresh data, as this is too massive to anyone to work on apparently.
/assign

**Comment by tuminoid** [comment]
Created 8 issues linked above for the dead links. These are real issues.

In additiion, there are plenty of internal false positives, where the link checker checks for absolute links and does not understand internal, generated links. (`.md` gets generated into `.html`).  Those we need to exclude in the checker config, when introducing it later, after the 8 linked issues are fixed.

This issue is now done. Thanks for everyone who contributed so far.

/close
