### ISSUE TITLE
Document user-data, meta-data and network-data usage with BareMetalHosts

### ISSUE THREAD

**Issue by lentzi90** [metal3-io/metal3-docs#401]
Add a section "BareMetalHost" in the [user guide](https://book.metal3.io/introduction.html) under Baremetal Operator. The relevant code can be found [here](https://github.com/metal3-io/metal3-docs/tree/main/docs/user-guide/src).

Add the information about user-data, meta-data and network-data to this section from [here](https://github.com/metal3-io/cluster-api-provider-metal3/blob/686d7e69531b21eb9370edaf0f72d017d3e037e9/docs/api.md?plain=1#L12-L34). Feel free to update the content to make it better, for example write out BareMetalHost instead of `CR` or `BMH`.

**Comment by dtantsur** [comment]
/remove-lifecycle stale
/assign

This is on my radar now, although I might organize it slightly differently.
