### ISSUE TITLE
Add API reference

### ISSUE THREAD

**Issue by lentzi90** [metal3-io/metal3-docs#402]
Similar to [CAPIs API reference](https://cluster-api.sigs.k8s.io/reference/api_reference), create a section in the [user guide](https://book.metal3.io/introduction.html) with links to the relevant pages for https://doc.crds.dev and https://pkg.go.dev. We should have separate links for the Bare Metal Operator, Cluster API provider Metal3 and IP address manager.

Example for Bare Metal Operator:

- Custom Resource Definitions: https://doc.crds.dev/github.com/metal3-io/baremetal-operator@v0.5.0
- golang API documentation: https://pkg.go.dev/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1

The code for the user guide can be found [here](https://github.com/metal3-io/metal3-docs/tree/main/docs/user-guide/src).

**Comment by SafeEHA** [comment]
Hello @lentzi90 can you please assign this to me, also I need some clarification,  In the folder structure, should it be a folder `Reference` at the tail end of the user-guide, then inside there would be files for `Baremetal-operator,` `Ip-addresss-manger` and `Cluster API provider`. For each of the files I'll then provide links for https://doc.crds.dev/ and https://pkg.go.dev/

For example `Ip-address-manager` file would contain [https://doc.crds.dev/github.com/metal3-io/ip-address-manager]( https://doc.crds.dev/github.com/metal3-io/ip-address-manager) and [https://pkg.go.dev/github.com/metal3-io/ip-address-manager/api/v1alpha1](https://pkg.go.dev/github.com/metal3-io/ip-address-manager/api/v1alpha1)

Is this correct?

**Comment by lentzi90** [comment]
Thanks for taking this up!
/assign @SafeEHA 

It sounds correct to me. Please note that the sidebar structure comes from [SUMMARY.md](https://github.com/metal3-io/metal3-docs/blob/main/docs/user-guide/src/SUMMARY.md). It actually doesn't look for the folder structure, but please keep it consistent so it is easier to navigate :smile: 

Just like you said, we should have a separate point in the sidebar for `Reference` and then under that one for each of our main projects. :slightly_smiling_face:

**Comment by SafeEHA** [comment]
Kindly review https://github.com/metal3-io/metal3-docs/pull/406

**Comment by lentzi90** [comment]
Fixed in #406 
Proof: https://book.metal3.io/reference
/close
