### ISSUE TITLE
Running custom IPA in an environment where thereis no DHCP - preprovisioning image

### ISSUE THREAD

**Issue by agewagra** [metal3-io/metal3-docs#416]
Metal3 docs mentions that preprovisioning image is used to add preprovisioning network data to bmh. This enables each host to use its own deploy ramdisk image customised with an appropriate network configuration.

Docs:
https://github.com/metal3-io/metal3-docs/blob/main/design/baremetal-operator/image-builder-integration.md

What is expected to happen:
The network data should be applied on the baremetal server in the inspecting phase with IPA.

Issue:
IPA is still waiting for DHCP to assign an IP to the server.  We confirmed that the network data is added in the iso image in the /openstack/latest/network_data.json. But there is no way to disable waiting for DHCP from IPA.

Is there any way to disable DHCP or generate customized initramfs and kernel files from the source code of IPA by disabling DHCP?

**Comment by Rozzii** [comment]
Please take a look of my comment on the related Issue: https://github.com/metal3-io/baremetal-operator/issues/1664#issuecomment-2112679884
/triage needs-information

**Comment by agewagra** [comment]
Duplicate of this issue : [metal3-io/baremetal-operator#1664](https://github.com/metal3-io/baremetal-operator/issues/1664)
