### ISSUE TITLE
Fix dead links at kubebuilder-migration.md

### ISSUE THREAD

**Issue by tuminoid** [metal3-io/metal3-docs#440]
```
| FILE: ./design/baremetal-operator/kubebuilder-migration.md
| [✖] https://sdk.operatorframework.io/docs/building-operators/golang/project_migration_guide/
| 
| 16 links checked.
| 
| ERROR: 1 dead links found!
| [✖] https://sdk.operatorframework.io/docs/building-operators/golang/project_migration_guide/ → Status: 404
```

/triage accepted
/help
/good-first-issue

Split from https://github.com/metal3-io/metal3-docs/issues/328

**Comment by ayushrakesh** [comment]
@tuminoid
`FILE: ./design/baremetal-operator/kubebuilder-migration.md
| [✖] https://sdk.operatorframework.io/docs/building-operators/golang/project_migration_guide/`

Is this is the correct link?
 https://sdk.operatorframework.io/docs/building-operators/golang/migration/

**Comment by tuminoid** [comment]
> @tuminoid `FILE: ./design/baremetal-operator/kubebuilder-migration.md | [✖] https://sdk.operatorframework.io/docs/building-operators/golang/project_migration_guide/`
> 
> Is this is the correct link? https://sdk.operatorframework.io/docs/building-operators/golang/migration/

Yes, seems to be correct one. The content has changed a little, but the page is right.

/assign @ayushrakesh
