### ISSUE TITLE
Fix dead links at nodes-machines-and-hosts.md

### ISSUE THREAD

**Issue by tuminoid** [metal3-io/metal3-docs#441]
```
| FILE: ./design/nodes-machines-and-hosts.md
| [✖] https://kubernetes-sigs.github.io/cluster-api/common_code/machine_controller.html
| 
| 8 links checked.
| 
| ERROR: 1 dead links found!
| [✖] https://kubernetes-sigs.github.io/cluster-api/common_code/machine_controller.html → Status: 404
```

/triage accepted
/help
/good-first-issue

Split from https://github.com/metal3-io/metal3-docs/issues/328

**Comment by ayushrakesh** [comment]
@tuminoid 

| FILE: ./design/nodes-machines-and-hosts.md
| [✖] https://kubernetes-sigs.github.io/cluster-api/common_code/machine_controller.html

Is this is the correct link?
https://release-0-1.cluster-api.sigs.k8s.io/common_code/machine_controller.html

**Comment by tuminoid** [comment]
> @tuminoid
> 
> | FILE: ./design/nodes-machines-and-hosts.md | [✖] https://kubernetes-sigs.github.io/cluster-api/common_code/machine_controller.html
> 
> Is this is the correct link? https://release-0-1.cluster-api.sigs.k8s.io/common_code/machine_controller.html

That probably point to the version we originally linked to, but the current version we should link to is at https://cluster-api.sigs.k8s.io/developer/architecture/controllers/machine

Do you agree @dtantsur ?

**Comment by geekrypter** [comment]
Hi @tuminoid, can I work on this issue? 

Also, can you confirm if https://cluster-api.sigs.k8s.io/developer/architecture/controllers/machine is the correct link as mentioned earlier?

**Comment by tuminoid** [comment]
IMO it is.

/assign @geekrypter
