### ISSUE TITLE
Fix dead links at capm3-remediation-controller-proposal.md

### ISSUE THREAD

**Issue by tuminoid** [metal3-io/metal3-docs#442]
```
| FILE: ./design/cluster-api-provider-metal3/capm3-remediation-controller-proposal.md
| [✖] https://cluster-api.sigs.k8s.io/tasks/healthcheck.html
| [✖] https://github.com/metal3-io/metal3-docs/blob/main/design/baremetal-operator/re-introspection-interface.md
| 
| 6 links checked.
| 
| ERROR: 2 dead links found!
| [✖] https://cluster-api.sigs.k8s.io/tasks/healthcheck.html → Status: 404
| [✖] https://github.com/metal3-io/metal3-docs/blob/main/design/baremetal-operator/re-introspection-interface.md → Status: 404
```

/triage accepted
/help
/good-first-issue

Split from https://github.com/metal3-io/metal3-docs/issues/328

**Comment by ayushrakesh** [comment]
Hey @tuminoid , is the two links are now correct?

| [✖] https://cluster-api.sigs.k8s.io/tasks/healthcheck.html
https://cluster-api.sigs.k8s.io/tasks/automated-machine-management/healthchecking

| [✖] https://github.com/metal3-io/metal3-docs/blob/main/design/baremetal-operator/re-introspection-interface.md
https://github.com/metal3-io/metal3-docs/blob/main/design/baremetal-operator/inspection-api.md

**Comment by tuminoid** [comment]
> Hey @tuminoid , is the two links are now correct?
> 
> | [✖] https://cluster-api.sigs.k8s.io/tasks/healthcheck.html https://cluster-api.sigs.k8s.io/tasks/automated-machine-management/healthchecking

This is correct. We can see with Wayback Machine they're talking about the same thing: https://web.archive.org/web/20220711120457/https://cluster-api.sigs.k8s.io/tasks/healthcheck.html

> | [✖] https://github.com/metal3-io/metal3-docs/blob/main/design/baremetal-operator/re-introspection-interface.md https://github.com/metal3-io/metal3-docs/blob/main/design/baremetal-operator/inspection-api.md

Yes, that is correct as well.

Would you make a PR to fix these?

**Comment by ayushrakesh** [comment]
@tuminoid Yes, want to make a PR.

**Comment by ayushrakesh** [comment]
@tuminoid Please review my PR.
