### ISSUE TITLE
Fix dead links at triage.md

### ISSUE THREAD

**Issue by tuminoid** [metal3-io/metal3-docs#445]
```
| FILE: ./processes/triage.md
| [✖] https://github.com/issues?utf8=%E2%9C%93&q=archived%3Afalse+user%3Ametal3-io+no%3Alabel+is%3Aissue+sort%3Acreated-asc+is%3Aopen
| [✖] https://github.com/issues?utf8=%E2%9C%93&q=archived%3Afalse+user%3Ametal3-io+is%3Aissue+sort%3Acreated-asc+is%3Aopen+label%3Apriority%2Fawaiting-more-evidence
| [✖] https://github.com/issues?q=archived%3Afalse+user%3Ametal3-io+is%3Aissue+sort%3Acreated-asc+is%3Aopen+label%3Alifecycle%2Fstale
| 
| 3 links checked.
| 
| ERROR: 3 dead links found!
| [✖] https://github.com/issues?utf8=%E2%9C%93&q=archived%3Afalse+user%3Ametal3-io+no%3Alabel+is%3Aissue+sort%3Acreated-asc+is%3Aopen → Status: 404
| [✖] https://github.com/issues?utf8=%E2%9C%93&q=archived%3Afalse+user%3Ametal3-io+is%3Aissue+sort%3Acreated-asc+is%3Aopen+label%3Apriority%2Fawaiting-more-evidence → Status: 404
| [✖] https://github.com/issues?q=archived%3Afalse+user%3Ametal3-io+is%3Aissue+sort%3Acreated-asc+is%3Aopen+label%3Alifecycle%2Fstale → Status: 404
| 
```

/triage accepted
/help
/good-first-issue

Split from https://github.com/metal3-io/metal3-docs/issues/328

**Comment by aditya7302** [comment]
@tuminoid These links are not giving status 404 on my browser.
![image](https://github.com/metal3-io/metal3-docs/assets/110886184/dbe46f3b-2836-425f-8712-e581060c4f7b)
![image](https://github.com/metal3-io/metal3-docs/assets/110886184/a679ee40-dcd9-4282-9486-4b75839f2926)
![image](https://github.com/metal3-io/metal3-docs/assets/110886184/8d12e538-9818-492a-b413-df4a8ff275a0)

**Comment by tuminoid** [comment]
> @tuminoid These links are not giving status 404 on my browser. ![image](https://private-user-

They are 404 when queried by a bot/command line tool, but not when queried with a browser.

```
curl "https://github.com/issues?utf8=%E2%9C%93&q=archived%3Afalse+user%3Ametal3-io+no%3Alabel+is%3Aissue+sort%3Acreated-asc+is%3Aopen"
Not Found
```

So to fix these, we need to fix config of the link checker to present itself as a legit user.

**Comment by priyanshsao** [comment]
can you tell me where is the link checker file located?

**Comment by tuminoid** [comment]
> can you tell me where is the link checker file located?

It does not exist in this repository yet, as we need to fix these dead links before introducing it. Output is from running the https://github.com/metal3-io/cluster-api-provider-metal3/blob/main/.github/workflows/lint-docs.yaml locally in this repo.

**Comment by tuminoid** [comment]
/close

We will switch the link checker to a better one, and these false positives do not need fixing right now.
