### ISSUE TITLE
Add ironic authentication

### ISSUE THREAD

**Issue by maelk** [metal3-io/metal3-docs#92]
Considering the self-managed cluster use-case, Ironic would run on the target cluster, in host networking mode. hence, all nodes would need physical access to the provisioning network, to be able to host ironic. However, by default, all traffic from the pods is NATed and routed, meaning that all pods could interact with ironic.

Currently there is no authentication in Ironic, making this setup very insecure. We should investigate adding some authentication in ironic. This issue is to keep track of securing the ironic setup.

**Comment by juliakreger** [comment]
Ironic presently has https://review.opendev.org/#/c/727467 in code review which would add authentication support to it's API surface, which has the advantage of not adversely impacting the lookup and heartbeat endpoints. So in essence, we would need to do the same with ironic-inspector, and client libraries including gopher cloud.

I guess the big question in my mind, is this sufficient, or is more needed?

/cc @iurygregory

**Comment by maelk** [comment]
If we are using simple authentication, then we will probably want to use https where possible, to avoid password to go in plain text in the requests.

**Comment by juliakreger** [comment]
I completely agree, I guess the question is how will cert data be passed in so endpoints could be started and validated when using https.

I guess another question is how do we phase this in?

**Comment by maelk** [comment]
I would propose to use cert-manager, that would allow the users deploying BMO to go with their own CA, or with self-signed certificates (we could make that default). The phasing will be tricky as multiple components need to be updated at once. Maybe we could leverage the v1alpha2 work to put that in at the same time ? If we need it faster, we will need another solution.
Maybe the deployment repo idea from Doug would help us go around that problem, we could have the old way of deploying ironic without https, while we step by step introduce a https based setup, and then do the whole shift at once from an http to an https deployment.

**Comment by maelk** [comment]
Pete Birley suggested to run ironic behind Apache and use its features for authentication and TLS : https://docs.openstack.org/ironic/pike/install/include/configure-ironic-api-mod_wsgi.html

**Comment by dtantsur** [comment]
We can use Apache or any other production WSGI container.

**Comment by maelk** [comment]
Here is a WIP design proposal : https://docs.google.com/document/d/1QsoA7M5ndfw15iE4tMWmBMv-wPVo8faoo1uNgn676W4/edit#

**Comment by zaneb** [comment]
HTTP Basic auth support is now available in the ironic containers and BMO. We could close this issue as fixed and open a fresh one for mTLS auth (which I think is still our long-term preferred option), or just keep this open.

**Comment by maelk** [comment]
I would like to keep this one open at least until we have implemented TLS (for a more secure basic auth). We are encountering issue with mTLS PHA not being supported in Go, so mTLS needs a re-design to avoid having multiple endpoints with and without client cert. but we could go with TLS for now at least.

**Comment by zaneb** [comment]
Fair enough.
/remove-lifecycle stale

**Comment by hustlzp1981** [comment]
I see that we have already got https + auth ready, propose to close this ticket, OK?

**Comment by maelk** [comment]
The end goal here was to achieve mTLS. We still do not support it. At this point we can either close this and open a new one for mTLS of keep track of the mTLS here (and rename this issue)

**Comment by zaneb** [comment]
Let's open a new issue for mTLS. If we have TLS + basic auth that counts as at least having authentication, I'd consider mTLS to be an enhancement.
